ls:
  src/components:
    .dir: PascalCase
    .module.scss: kebab-case
    .props.tsx: kebab-case
    .tsx: PascalCase
  src/hooks:
    .dir: kebab-case
    .tsx: kebab-case
  src/layouts:
    .dir: kebab-case
    .module.scss: kebab-case
    .props.tsx: kebab-case
    .tsx: kebab-case
  src/pages:
    .dir: kebab-case
    .tsx: PascalCase
  src/styles:
    .dir: kebab-case
    .module.scss: kebab-case
    .scss: kebab-case
  src/utils:
    .dir: kebab-case
    .tsx: kebab-case

ignore:
  - src/pages/_app.tsx
  - src/components